# Use official node image
FROM node:20-alpine

WORKDIR /usr/src/app

# Install dependencies first to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy rest of the source code
COPY . .

# Build the app (if using ts)
RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD ["node", "dist/main.js"]
